import{a as y,S as b,i as d}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v=document.querySelector(".form"),u=document.querySelector(".input-name"),n=document.querySelector(".loader"),L=document.querySelector(".gallery"),l=document.querySelector(".load-btn");let m=0,p=1;const f=y.create({baseURL:"https://pixabay.com/api/",params:{key:"42310325-d8e2b88bd4f4d7db9639050a5",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}}),w=new b(".image-link",{captionsData:"alt",captionDelay:250});async function S(t){t.preventDefault();const o=u.value.trim();if(!o){c("Please enter a search query");return}try{n.classList.add("visible");const i=(await f.get("",{params:{q:o}})).data;m=i.totalHits,g(i.hits)}catch(s){console.error("Error fetching data:",s),c("Error fetching data. Please try again later.")}finally{n.classList.remove("visible")}}function g(t){if(t.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}L.innerHTML=t.map(q).join(""),w.refresh(),$()}function q(t){const{webformatURL:o,largeImageURL:s,tags:i,likes:e,views:r,comments:a,downloads:h}=t;return`
    <li class="photo">
      <div class="photo-card">
        <a class="image-link" data-lightbox="image" href="${s}">
          <img class="gallery-image" data-source="${s}" src="${o}" alt="${i}">
        </a>
      </div>
      <div class="description">
        <p class="description-item"> Likes ${e}</p>
        <p class="description-item"> Views ${r}</p>
        <p class="description-item"> Comments ${a}</p>
        <p class="description-item"> Downloads ${h}</p>
      </div>
    </li>`}async function P(){try{n.classList.add("visible");const t=await f.get("",{params:{q:u.value.trim(),page:++p}});g(t.data.hits),E()}catch(t){console.error("Error fetching data:",t)}finally{n.classList.remove("visible")}k()}function c(t){d.error({title:"Error",message:t,backgroundColor:"red",messageColor:"white",messageSize:"25"})}function E(){const t=document.querySelector(".photo").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function $(){l.style.visibility="visible"}function C(){l.style.visibility="hidden"}function k(){m<=p*15&&(C(),d.info({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#125487",messageColor:"white",messageSize:"25"}))}v.addEventListener("submit",S);l.addEventListener("click",P);
//# sourceMappingURL=commonHelpers.js.map
